version: '3.9'

services:
  BookStoreFull_mysql:
    image: mysql
    restart: on-failure
    ports:
      - "3311:3306"
    volumes:
      - ms_database:/var/lib/BookStoreFull
    networks:
      - ms_network
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'BookStoreFull'
  redis:
    container_name: redis-BookStore
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - ms_database:/var/lib/redis


volumes:
  ms_database:

networks:
  ms_network: