
spring:
  messages:
    encoding: UTF-8
    basename: messages
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  main:
    allow-circular-references: true
  profiles:
    include:
      - db

  mail:
    host: smtp.gmail.com
    port: 587
    username: raufbayramov036@gmail.com
    password: heuznvzcshettylp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true